### ISSUE TITLE
Project backlog management issue

### ISSUE THREAD

**Issue by sleepylee** [ankitkalia1195/elixir-google-crawler#27]
## What happened
- The tickets are not following our format git-template/issue_template https://github.com/nimblehq/git-template/tree/main/.github/ISSUE_TEMPLATE.
- Few small issues with backlog management.

## Expectation
- First, it should follow the template we provided, for instances, these are not:
  - https://github.com/ankitkalia1195/elixir-google-crawler/issues/3
  - https://github.com/ankitkalia1195/elixir-google-crawler/issues/6
- Second, it would be nice to have differentiation between [UI] [Backend] [Integration]. Otherwise, take this issue https://github.com/ankitkalia1195/elixir-google-crawler/issues/3 as an example: a big PR will be produced with everything packed in 1 place and it wouldn't be nice for the reviewer nor the author to validate the implementation themselves.

Regarding the backlog management:
- It was nice that you have adopted the recent practice we just announced 👍  with the labeling & milestone management, though you may want to close the milestone on time i.e: `v0.1.0` as well:
![image](https://user-images.githubusercontent.com/13435717/117760750-6cf42700-b250-11eb-8759-208862c5f633.png)

- Minor: try to remove the typo label, just for a clean state:
![image](https://user-images.githubusercontent.com/13435717/117760817-84331480-b250-11eb-830f-d809e9bafc41.png)

**Comment by ankitkalia1195** [comment]
@sleepylee Can you check the tickets again, I did the following changes

* Applied our github issue template, altough I feel that the format doesnt suite ICs that much, the who_benefits section will always be User mostly 😆 
* I am not creating seperate frontend and backend tickets for all tickets, as in many cases I will be using phoenix generators or libraries. Then often both frontend and backend code can be generated at once. Only in cases where I will not be using a generator, I labelled some stories as [BACKEND] and [FRONTEND].
* Added milestone labels to the issues
* Made a release for 0.1.0

**Comment by sleepylee** [comment]
sorry for the late response, @ankitkalia1195. Indeed it was not very necessary in this case for the `Who Benefit` section. It is supposed more likely the normal backlog ticket template should be used in this case. Anyway, the changes are making the backlog overall looks better now 👍
